account/urls.py
from django.urls import path
from . import views


app_name = 'account'


urlpatterns = [
    path('dashboard/', views.dashboard, name="dashboard"),
    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),
    path('signup/', views.user_signup, name="signup"),
    path('edit_profile/', views.edit_profile, name="edit_profile"),
    path('password_change/', views.password_change, name="password_change")
]

board/urls.py
from django.urls import path
from . import views

app_name = 'board'


urlpatterns = [
    # path('', views.homepage, name="homepage"),
    path('add_category/', views.add_category, name="add_category"),
    path('add_post/', views.add_post, name="add_post"),
    path('categories/', views.category_list, name="category_list"),
    path('<str:title>/', views.category_detail, name="category_detail"),
    path('<str:category>/<int:id>/<str:title>/', views.post_detail, name="post_detail"),
]

forum/urls.py
from django.contrib import admin
from . import views
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name="homepage"),
    path('account/', include('account.urls', namespace='account')),
    path('board/', include('board.urls', namespace='board')),
]

board/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

from account.models import UserProfile


class Category(models.Model):
    admin = models.ManyToManyField(UserProfile,
                                   limit_choices_to={'is_admin': True})
    title = models.CharField(max_length=100, unique=True)
    description = models.TextField()
    active = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('board:category_detail',
                       kwargs={'title': self.title})


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    date_edited = models.DateTimeField(auto_now=True)
    approved = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('board:post_detail',
                       kwargs={'category': self.category,
                               'id': self.id,
                               'title': self.title})


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    parent = models.ForeignKey('self', 
                              on_delete=models.CASCADE,
                              blank=True,
                              null=True,
                              related_name='replies')
    body = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['date_created',]

    def __str__(self):
        return f'{self.user.username}\'s comment'

board/forms.py
from django import forms
from .models import Category, Post, Comment


class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = ['admin', 'title', 'description']


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'category', 'content']


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['body']
        # widgets = {'content': forms.TextInput}

board/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .forms import CategoryForm, CommentForm,  PostForm
from .models import Category, Post, Comment


# def homepage(request):
#     categories = Category.objects.filter(active=True)
#     latest_posts = Post.objects.order_by('-date_created')

#     return render(request,
#                   "board/homepage.html",
#                   {'categories': categories,
#                    'latest_posts': latest_posts})


def category_list(request):
    categories = Category.objects.filter(active=True)

    return render(request,
                  'board/category_list.html',
                  {'categories': categories,
                   'section': 'category_list'})


def category_detail(request, title):
    category = Category.objects.get(title=title)
    posts = category.post_set.filter(approved=True)

    return render(request,
                  'board/category_detail.html',
                  {'posts': posts,
                   'category': category,
                   'section': 'category_detail'})


def post_detail(request, category, id, title):
    post = get_object_or_404(Post, id=id)
    comments = Comment.objects.all().filter(
        active=True, post=post, parent__isnull=True)

    new_comment = None

    if not post.approved:
        messages.error(request, "Post not found")
        return redirect('homepage')

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)

        if comment_form.is_valid():
            parent_obj = None

            try:
                parent_id = int(request.POST.get('parent_id'))
            except:
                parent_id = None

            if parent_id:
                parent_obj = Comment.objects.get(id=parent_id)

                if parent_obj:
                    reply_comment = comment_form.save(commit=False)
                    reply_comment.parent = parent_obj

            new_comment = comment_form.save(commit=False)

            new_comment.post = post
            new_comment.user = request.user

            new_comment.save()

            messages.success(request, 'Comment added successfully')
            return redirect(post.get_absolute_url())
    else:
        comment_form = CommentForm()

    return render(request,
                  'board/post_detail.html',
                  {'post': post,
                   'comments': comments,
                   'comment_form': comment_form,
                   'section': 'post_detail'})


@login_required()
def add_category(request):

    if not request.user.userprofile.is_admin:
        messages.error(request, "Only admins can add categories.")
        return redirect('homepage')

    if request.method == 'POST':
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, 'Category has been added.')
            return redirect('homepage')

    else:
        form = CategoryForm()

    return render(request,
                  'board/add_category.html',
                  {'form': form,
                   'section': 'add_category'})


@login_required()
def add_post(request):

    if request.method == 'POST':
        form = PostForm(request.POST)

        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            form.save()

            post_title = form.cleaned_data['title']

            messages.success(request, f"'{post_title}' posted successfully.")

            return redirect('homepage')

    else:
        form = PostForm()

    return render(request,
                  'board/add_post.html',
                  {'form': form,
                   'section': 'add_post'})

board/templates/board/add_category.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    Create Category
{% endblock title %}
    
{% block styles %}
    <link href="{% static "css/bootstrap.css" %}" rel="stylesheet" type="text/css">
    <link href="{% static "css/style.css" %}" rel="stylesheet" type="text/css">
    <link href="{% static "css/font-awesome.min.css" %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/loginstyle.css' %}">
{% endblock styles %}

{% block content %}
<section class="main-content920" style="margin-bottom: 10px;">
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <div class="ask-question-input-part032">
                    <h4>Add a Category</h4>
                    <form method="post">
                        <div class="details2-239">
                            <span class="form-description43305">
                                <label>{{ form.title.label }}</label>
                            </span>
                            {{ form.title }}
                        </div>

                        <div class="categori49">
                            <span class="form-description43305">
                                <label>{{ form.admin.label }}</label>
                            </span>
                            {{ form.admin }}
                        </div>

                        <div class="details2-239">
                            <div class="form-description43305">
                                <label>
                                    {{ form.description.label }}
                                </label>
                            </div>
                            {{ form.description }}
                            {{ form.description.error }}
                        </div>

                        {% csrf_token %}

                        <div class="publish-button2389">
                            <input type="submit" class="publis1291" value="Post">
                        </div>
                    </form>
                </div>
            </div>
            {% include 'side_bar.html' %}
        </div> 
    </div>
</section>

{% block scripts %}
    <script src="{% static "js/jquery-1.12.4.min.js" %}"></script>
    <script src="{% static "js/jquery-2.2.4.min.js" %}"></script>
    <script src="{% static "js/jquery-3.1.1.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/npm.js" %}"></script>
{% endblock scripts %}

{% endblock content %}
    

board/templates/board/add_post.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
Create Post
{% endblock title %}

{% block styles %}
    <link href="{% static "css/bootstrap.css" %}" rel="stylesheet" type="text/css">
    <link href="{% static "css/style.css" %}" rel="stylesheet" type="text/css">
    <link href="{% static "css/font-awesome.min.css" %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/loginstyle.css' %}">
{% endblock styles %}

{% block content %}
<section class="main-content920" style="margin-bottom: 10px;">
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <div class="ask-question-input-part032">
                    <h4>Post Something</h4>
                    <form method="post">
                        <div class="question-title39">
                            <span class="form-description43305">
                                <label>{{ form.title.label }}</label>
                            </span>
                            {{ form.title }}
                        </div>

                        <div class="categori49">
                            <span class="form-description43305">
                                <label>{{ form.category.label }}</label>
                            </span>
                            {{ form.category }}
                        </div>

                        <div class="details2-239">
                            <div class="form-description43305">
                                <label>
                                    {{ form.content.label }}
                                </label>
                            </div>
                            {% comment %} <textarea id="txtEditor"></textarea> {% endcomment %}
                            {{ form.content }}
                        </div>

                        {% csrf_token %}

                        <div class="publish-button2389">
                            <input type="submit" class="publis1291" value="Post">
                        </div>
                    </form>
                </div>
            </div>
            {% include 'side_bar.html' %}
        </div>
    </div>
</section>

{% block scripts %}
    <script src="{% static "js/jquery-1.12.4.min.js" %}"></script>
    <script src="{% static "js/jquery-2.2.4.min.js" %}"></script>
    <script src="{% static "js/jquery-3.1.1.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/npm.js" %}"></script>
{% endblock scripts %}

{% endblock content %}

board/templates/board/category_detail.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    {{ category.title|title }}
{% endblock title %}

{% block styles %}
    <link href="{% static "css/bootstrap.css" %}" rel="stylesheet" type="text/css">
    <link href="{% static "css/style.css" %}" rel="stylesheet" type="text/css">
    <link href="{% static "css/font-awesome.min.css" %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
{% endblock styles %}

{% block content %}
<section class="main-content920">
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <div class="about-user2039 mt-70">
                    <div class="user-title3930">
                        <h3>
                            {{ category.title|title }}
                        </h3>
                        <hr>
                    </div>

                    <div class="user-description303">
                        <p>
                            {{ category.description }}
                        </p>
                    </div>

                    <div class="ques-icon-info3293">
                        <i class="fa fa-users">
                            admins:
                            {% for admin in category.admin.all %}
                                {% if not forloop.last %}
                                    {{ admin.user.username }},
                                {% else %}
                                    {{ admin.user.username }}.
                                {% endif %}
                            {% endfor %}
                        </i>
                        <i class="fa fa-paper-plane-o">
                            {{ category.post_set.all.count }} 
                            Post{{ category.post_set.all.count|pluralize }}
                        </i>
                    </div>
                </div>

                <h3>Posts</h3>

                {% for post in category.post_set.all %}

                <div class="question-type2033">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="right-description893">
                                <div id="que-hedder2983">
                                    <h3>
                                        <a href="{{ post.get_absolute_url }}">
                                            {{ post.title|title }}
                                        </a>
                                    </h3>
                                </div>

                                <div class="ques-details10018">
                                    <p>
                                        {% comment %} {{ post.content|truncatewords:30 }} {% endcomment %}
                                        {% lorem 1 p random %}
                                    </p>
                                </div>
                                <hr>

                                <div class="ques-icon-info3293">
                                    <a href="#">
                                        <i class="fa fa-user-o" aria-hidden="true">
                                            {{ post.user.username }}

                                            {% if post.user.userprofile.is_admin %}
                                            <span class="badge229">
                                                admin
                                            </span>
                                            {% endif %}
                                        </i>
                                    </a>
                                    <a href="{{ post.category.get_absolute_url }}">
                                        <i class="fa fa-folder-open-o" aria-hidden="true">
                                            {{ post.category }}
                                        </i>
                                    </a>

                                    <span>
                                        <i class="fa fa-calendar-o" aria-hidden="true">
                                            {% comment %} {% now "DATE_FORMAT" as current_date %} {% endcomment %}
                                            {{ post.date_edited|date:"jS F Y H:i" }}
                                        </i>
                                    </span>
                                    <a href="#">
                                        <i class="fa fa-heart-o" aria-hidden="true">
                                            {% comment %} Implemet like functionality {% endcomment %}
                                        </i>
                                    </a>
                                    <span>
                                        <i class="fa fa-comments-o">
                                            {{ post.comment_set.count }} Comment{{ post.comment_set.count|pluralize }}
                                        </i>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% empty %}
                <p>
                    There are no posts here.
                </p>
                {% endfor %}

            </div>
            {% include 'side_bar.html' %}
        </div>
    </div>
</section>

{% endblock content %}

board/templates/board/post_detail.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
{{ post.title|title }} | {{ post.category.title }}
{% endblock title %}


{% block styles %}
    <link href="{% static "css/bootstrap.css" %}" rel="stylesheet" type="text/css">
    <link href="{% static "css/style.css" %}" rel="stylesheet" type="text/css">
    <link href="{% static "css/font-awesome.min.css" %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400" rel="stylesheet">
    <link rel="stylesheet" href="{% static "css/normalize.css" %}">
    <link rel="stylesheet" href="{% static "css/loginstyle.css" %}">
{% endblock styles %}


{% block content %}

<section class="main-content920">
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <div class="post-details">
                    <div class="details-header923">
                        <div class="row">
                            <div class="col-md-8">
                                <div class="post-title-left129">
                                    <h3>{{ post.title|title }}</h3>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                    <div class="post-details-info1982">
                        <p>
                            {{ post.content|linebreaks|safe }}
                            {% lorem 1 p random %}
                        </p>
                        <hr>
                        <div class="post-footer29032">
                            <div class="l-side2023">

                                <i class="fa fa-user-o">
                                    {{ post.user.username}}
                                </i>

                                <a href="{{ post.category.get_absolute_url }}">
                                    <i class="fa fa-folder folder2" aria-hidden="true">{{ post.category }}</i>
                                </a>

                                <i class="fa fa-calendar-o" aria-hidden="true"> {{ post.date_edited }} </i>

                                <a href="#">
                                    <i class="fa fa-heart-o" aria-hidden="true"> </i>
                                </a> 

                                <a href="#">
                                    <i class="fa fa-comments-o " aria-hidden="true"> {{ comments.count }} Comment{{ comments.count|pluralize }}</i>
                                </a> 
                                
                            </div>
                            
                        </div>
                    </div>
                </div>
               
                
                <div class="comment-list12993">
                    <div class="container">
                        <div class="row">

                            <div class="comments-container">
                                {% if comments %}
                                    <ul id="comments-list" class="comments-list">
                                        {% for comment in comments %}
                                            {% if comment.post.id == post.id %}
                                                <li>
                                                    <div class="comment-main-level">
                                                        <!-- Contenedor del Comentario -->
                                                        <div class="comment-box">
                                                            <div class="comment-head">

                                                                <h6 class="comment-name">
                                                                    {{ comment.user.username }}    
                                                                </h6>

                                                                <span>
                                                                    <i class="fa fa-calendar-o" aria-hidden="true">
                                                                        {{ comment.date_created }}
                                                                    </i>
                                                                </span>

                                                            </div>
                                                            
                                                            <div class="comment-content">
                                                                {{ comment.body }}
                                                            </div>
                                                        </div>
                                                    </div>

                                                    
                                                    {% for reply in comment.replies.all %}
                                                        <ul class="comments-list reply-list">
                                                            <li>
                                                                <div class="comment-box">
                                                                    <div class="comment-head">
                                                                        <h6 class="comment-name">
                                                                            {{ reply.user.username }}
                                                                        </h6>
                                                                        <span>
                                                                            <i class="fa fa-clock-o" aria-hidden="true"> 
                                                                                {{ reply.date_edited }}
                                                                            </i>
                                                                        </span> 
                                                                    </div>
                                                                    <div class="comment-content"> 
                                                                        {{ reply.body }}
                                                                    </div>
                                                                </div>
                                                            </li>  
                                                        </ul>
                                                    {% endfor %}

                                                    {% if request.user.is_authenticated %}
                                                        <div class="comment289-box">
                                                            
                                                            <div class="row">
                                                                <div class="col-md-5 reply-list">
                                                                    <form method="post">
                                                                        <div class="post9320-box">
                                                                            <label style="display: none;">
                                                                                {{ comment_form.body.label }}
                                                                            </label>
                                                                            <span class="reply-box">
                                                                                Reply: {{ comment_form.body }}
                                                                            </span>
                                                                        </div>
                                                                        {% csrf_token %}
                                                                        <input type="hidden" name="parent_id" value="{{ comment.id }}">
                                                                        <input type="submit" class="btn btn-default" value="Reply">
                                                                    </form>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    {% else %}
                                                        <span class="reply-list">
                                                            <a href="{% url 'account:login' %}?next={{ request.path }}">Login</a> to reply.
                                                        </span>
                                                    {% endif %}
                                                </li>
                                            {% endif %}
                                        {% endfor %}  
                                    </ul>
                                {% else %}
                                    <p>Be the first to comment</p>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>


                {% if request.user.is_authenticated %}
                    <div class="comment289-box">
                        <hr>
                        <div class="row">
                            <div class="col-md-12">
                                <form method="post">
                                    <div class="post9320-box">
                                        <label style="display: none;">
                                            {{ comment_form.body.label }}
                                        </label>
                                            Comment: {{ comment_form.body }}
                                    </div>
                                    {% csrf_token %}
                                    <input type="submit" class="btn btn-default" value="Comment">
                                </form>
                            </div>
                        </div>
                    </div>
                {% else %}
                <hr>
                    <p>
                        <a href="{% url 'account:login' %}?next={{ request.path }}">Login</a> to comment.
                    </p>
                {% endif %}
            </div>
            {% include 'side_bar.html' %}
        </div>
    </div>
</section>

{% endblock content %}