account/urls.py
from django.urls import path
from . import views


app_name = 'account'


urlpatterns = [
    path('dashboard/', views.dashboard, name="dashboard"),
    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),
    path('signup/', views.user_signup, name="signup"),
    path('edit_profile/', views.edit_profile, name="edit_profile"),
    path('password_change/', views.password_change, name="password_change")
]

board/urls.py
from django.urls import path
from . import views

app_name = 'board'


urlpatterns = [
    # path('', views.homepage, name="homepage"),
    path('add_category/', views.add_category, name="add_category"),
    path('add_post/', views.add_post, name="add_post"),
    path('categories/', views.category_list, name="category_list"),
    path('<str:title>/', views.category_detail, name="category_detail"),
    path('<str:category>/<int:id>/<str:title>/', views.post_detail, name="post_detail"),
]

forum/urls.py
from django.contrib import admin
from . import views
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name="homepage"),
    path('account/', include('account.urls', namespace='account')),
    path('board/', include('board.urls', namespace='board')),
]

board/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

from account.models import UserProfile


class Category(models.Model):
    admin = models.ManyToManyField(UserProfile,
                                   limit_choices_to={'is_admin': True})
    title = models.CharField(max_length=100, unique=True)
    description = models.TextField()
    active = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('board:category_detail',
                       kwargs={'title': self.title})


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    date_edited = models.DateTimeField(auto_now=True)
    approved = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('board:post_detail',
                       kwargs={'category': self.category,
                               'id': self.id,
                               'title': self.title})


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    parent = models.ForeignKey('self', 
                              on_delete=models.CASCADE,
                              blank=True,
                              null=True,
                              related_name='replies')
    body = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['date_created',]

    def __str__(self):
        return f'{self.user.username}\'s comment'

board/forms.py
from django import forms
from .models import Category, Post, Comment


class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = ['admin', 'title', 'description']


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'category', 'content']


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['body']
        # widgets = {'content': forms.TextInput}

board/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .forms import CategoryForm, CommentForm,  PostForm
from .models import Category, Post, Comment


# def homepage(request):
#     categories = Category.objects.filter(active=True)
#     latest_posts = Post.objects.order_by('-date_created')

#     return render(request,
#                   "board/homepage.html",
#                   {'categories': categories,
#                    'latest_posts': latest_posts})


def category_list(request):
    categories = Category.objects.filter(active=True)

    return render(request,
                  'board/category_list.html',
                  {'categories': categories,
                   'section': 'category_list'})


def category_detail(request, title):
    category = Category.objects.get(title=title)
    posts = category.post_set.filter(approved=True)

    return render(request,
                  'board/category_detail.html',
                  {'posts': posts,
                   'category': category,
                   'section': 'category_detail'})


def post_detail(request, category, id, title):
    post = get_object_or_404(Post, id=id)
    comments = Comment.objects.all().filter(
        active=True, post=post, parent__isnull=True)

    new_comment = None

    if not post.approved:
        messages.error(request, "Post not found")
        return redirect('homepage')

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)

        if comment_form.is_valid():
            parent_obj = None

            try:
                parent_id = int(request.POST.get('parent_id'))
            except:
                parent_id = None

            if parent_id:
                parent_obj = Comment.objects.get(id=parent_id)

                if parent_obj:
                    reply_comment = comment_form.save(commit=False)
                    reply_comment.parent = parent_obj

            new_comment = comment_form.save(commit=False)

            new_comment.post = post
            new_comment.user = request.user

            new_comment.save()

            messages.success(request, 'Comment added successfully')
            return redirect(post.get_absolute_url())
    else:
        comment_form = CommentForm()

    return render(request,
                  'board/post_detail.html',
                  {'post': post,
                   'comments': comments,
                   'comment_form': comment_form,
                   'section': 'post_detail'})


@login_required()
def add_category(request):

    if not request.user.userprofile.is_admin:
        messages.error(request, "Only admins can add categories.")
        return redirect('homepage')

    if request.method == 'POST':
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, 'Category has been added.')
            return redirect('homepage')

    else:
        form = CategoryForm()

    return render(request,
                  'board/add_category.html',
                  {'form': form,
                   'section': 'add_category'})


@login_required()
def add_post(request):

    if request.method == 'POST':
        form = PostForm(request.POST)

        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            form.save()

            post_title = form.cleaned_data['title']

            messages.success(request, f"'{post_title}' posted successfully.")

            return redirect('homepage')

    else:
        form = PostForm()

    return render(request,
                  'board/add_post.html',
                  {'form': form,
                   'section': 'add_post'})

board/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    {% load custom_tags %}

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="language" content="English">

    <title>
        {% block title %}{% endblock title %}
    </title>

    {% comment %} <link href="{% static "css/bootstrap.css" %}" rel="stylesheet" type="text/css">
    <link href="{% static "css/style.css" %}" rel="stylesheet" type="text/css">
    <link href="{% static "css/font-awesome.min.css" %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
     {% endcomment %}

    {% block styles %}
    
    {% endblock styles %}
    
    {% comment %} <link rel="stylesheet" href="{% static "css/loginstyle.css" %}">
    <link href="{% static 'css/editor.css' %}" rel="stylesheet" type="text/css"> {% endcomment %}

</head>

<body>
    {% comment %} {% include 'welcome_header.html' %} {% endcomment %}

    {% if section != 'user_login' %}
        {% if section != 'user_signup' %}
            {% include "nav_bar.html" %}
        {% endif %}
    {% endif %}


    {% block content %}
        
    {% endblock content %}


    {% if section != 'user_login' %}
        {% if section != 'user_signup' %}
            {% include "footer.html" %}
        {% endif %}
    {% endif %}
    

    <script src="{% static "js/jquery-1.12.4.min.js" %}"></script>
    <script src="{% static "js/jquery-2.2.4.min.js" %}"></script>
    <script src="{% static "js/jquery-3.1.1.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/npm.js" %}"></script>
    <script src="{% static "js/editor.js" %}"></script>

    
    {% block scripts %}
        
    {% endblock scripts %}
        

</body>

</html>

board/templates/footer.html
{% load static %}

<section class="footer-social">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <p>
                    Built with: <img id="django-image"src="{% static "image/django-logo-negative.svg" %}" alt="django">
                </p>
            </div>

        </div>
    </div>
</section>

board/templates/nav_bar.html
{% load static %}

{% load custom_tags %}

<div class="top-menu-bottom932">
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false"> <span class="sr-only">Toggle
                        navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span
                        class="icon-bar"></span> </button>

                <a class="navbar-brand" href="{% url 'homepage' %}">Forum</a>

            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav"> </ul>
                <ul class="nav navbar-nav navbar-right">

                    <li><a href="{% url 'homepage' %}">Home</a></li>

                    <li class="dropdown"> <a href="{% url 'board:category_list' %}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        Post Categories<span class="caret"></span></a>

                        <ul class="dropdown-menu animated zoomIn">
                            {% show_category_list %}

                            <li>
                                <a href="{% url 'board:category_list' %}">
                                    <small>
                                        View all
                                    </small>
                                </a>
                            </li>
                        </ul>

                    </li>

                    {% if user.is_authenticated %}

                        <li>
                            <a href="{% url 'board:add_post' %}">
                                Post Something
                            </a>
                        </li>

                        {% if request.user.userprofile.is_admin %}    
                            <li>
                                <a href="{% url 'board:add_category' %}">
                                    Add Category
                                </a>
                            </li>
                        {% endif %}

                        <li>
                            <a href="{% url 'account:dashboard' %}">
                                Dashboard
                            </a>
                        </li>

                        {% if request.user.userprofile.is_admin %}
                            <li class="nav-admin-badge">
                                {% if request.user.userprofile.is_admin %}
                                    <span class="badge229">Admin</span>
                                {% endif %}
                            </li>
                        {% endif %}

                    {% else %}
                        <li>
                            <a href="{% url "account:login" %}?next={{ request.path }}">Login</a>
                        </li>
                        <li>
                            <a href="{% url 'account:signup' %}?next={{ request.path }}">Signup</a>
                        </li>
                    {% endif %}
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
</div>

board/templates/side_bar.html
{% load custom_tags %}

<aside class="col-md-3 sidebar97239">

    <div class="status-part3821">
        <h4>Forum Stats</h4> 
        {% forum_stats %}
    </div>
    
    <!--              login part-->
    {% comment %} <div class="login-part2389">
        <h4>Login</h4>
        {% conditional_login_form request %}
    </div> {% endcomment %}
    
    <!--        start recent post  -->
    <div class="recent-post3290">
        <h4>Recent Post</h4>
        {% recent_posts %}
    </div>
    <!--       end recent post    -->
</aside>

board/templates/welcome_header.html
<section class="welcome-part-one">
    <div class="container">
        <div class="welcome-demop102 text-center">
            <h2>Welcome to Ask me, Awesome Questions & Answer Template</h2>
            <p>Duis dapibus aliquam mi, eget euismod sem scelerisque ut. Vivamus at elit quis urna adipiscing
                iaculis. Curabitur vitae velit in neque dictum blandit. Proin in iaculis neque. Pellentesque
                <br> habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur
                vitae velit in neque dictum blandit
            </p>
            <div class="button0239-item">
                <a href="#">
                    <button type="button" class="aboutus022">About Us</button>
                </a>
                <a href="#">
                    <button type="button" class="join92">Join Now</button>
                </a>
            </div>
            <div class="form-style8292">
                <div class="input-group"> <span class="input-group-addon"><i class="fa fa-pencil-square"
                            aria-hidden="true"></i></span>
                    <input type="text" class="form-control form-control8392"
                        placeholder="Ask any question and you be sure find your answer ?"> <span
                        class="input-group-addon"><a href="#">Ask Now</a></span>
                </div>
            </div>
        </div>
    </div>
</section>